hmcts/prl-e2e-tests

Jenkinsfile_CNP
e2e/common/changedTestsRunner.ts
e2e/tests/manageCases/caseList/caseList.spec.ts
e2e/tests/manageCases/createCase/C100/c100ApplicantDetails.spec.ts
package.json
yarn.lock

Background:
We have seen wide scale performance issues on the pipelines due to each PR running the full automation suite, regardless of changes made in the pipeline only to a small fraction of those tests.
Solution:
Implement a changedTestRunner class that only runs the changed tests on PR, and ignores the rest. The full suite will be run on master.
[PRL-6237](https://tools.hmcts.net/jira/browse/PRL-6237)

Only run required tests

---

Jenkinsfile_nightly

jenkins config update to change nightly pipeline run

Change nightly pipeline run to 5pm

---

e2e/common/idamCreateCitizenUserApiHelper.ts

Add status code check for IDAM API

---

e2e/common/createCaseHelper.ts
e2e/common/idamLoginHelper.ts
e2e/tests/global.setup.ts

small fixes to case creator and bearer token env name

fix citizen test

---

e2e/pages/manageCases/caseList/caseListPage.ts

Remove implicit waits

---

Jenkinsfile_nightly

nightly-pipeline-time-update

---

Jenkinsfile_nightly

Fix report name

---

e2e/fixtures/citizen/createCase/C100/reviewPages/caJourneyEmergencyProtectionReviewContent.ts
e2e/fixtures/citizen/createCase/C100/reviewPages/caJourneyExistingMIAMReviewContent.ts
e2e/fixtures/citizen/createCase/C100/reviewPages/caJourneyMIAMHearingUrgencyReviewContent.ts
e2e/fixtures/citizen/createCase/C100/reviewPages/caJourneyWrittenConsentReviewContent.ts
e2e/fixtures/citizen/createCase/C100/safetyConcerns/childConcerns/childSafetyConcernsCommonContent.ts
e2e/fixtures/citizen/createCase/C100/safetyConcerns/concernAboutContent.ts

amend content files following recent changes to UI

Fix citizen tests: remove "optional" from content files

---

package.json
yarn.lock

Remove pre-commit from package.json 
- Will also need to delete your local pre-commit hook file locally

Remove pre-commit from package.json

---

e2e/fixtures/citizen/createCase/C100/pay/payContent.ts

update card expiry date to fix citizen tests

---

e2e/common/selectors.ts
e2e/fixtures/citizen/caseView/uploadDocuments/uploadContent.ts
e2e/journeys/citizen/caseView/uploadDocuments/upload.ts
e2e/pages/citizen/caseView/uploadDocuments/uploadPage.ts
e2e/tests/citizen/caseView/uploadDocuments/applicant/uploadDocuments.spec.ts

Name of event: DA applicant dashboard
Number of pages: 1
User(s) to complete event: Citizen
Dependency:
courtNav create case
Court admin has completed "check application" WA
Court admin has completed "send to gatekeeper" WA
Judge has complete "direction of issue" WA
Court Admin has completed "complete order" WA
Court Admin has completed "Service of application
Logged in as a citizen as case has been activated so you can see the applicant dashboard
Definition of done:
All happy and accessibility journeys are automated.
Jenkins PR build is passing and green.
https://tools.hmcts.net/jira/browse/PRL-6691

PRL-6691 Upload Documents Task Page

---

e2e/common/accessCodeHelper.ts

Fix access code helper user after updating the secret

Fix access code helper user after updating the secret

---

e2e/pages/manageCases/caseProgression/sendAndReplyToMessages/sendAndReplyToMessagesSubmitPage.ts

Fix send and reply to messages tests

Fix send and reply to messages tests

---

package.json

add nightly tests to regression test run

---

README.md
package.json

Changing `yarn configure` to `yarn setup` which also included installing deps and populating the .env file with secrets

Change configure script to setup script + install deps and run secret script

---

e2e/common/commonStaticText.ts
e2e/fixtures/manageCases/caseProgression/withdrawApplication/withdrawApplicationEvent1Content.ts
e2e/fixtures/manageCases/caseProgression/withdrawApplication/withdrawApplicationEventConfirmContent.ts
e2e/fixtures/manageCases/caseProgression/withdrawApplication/withdrawApplicationEventSubmitContent.ts
e2e/journeys/manageCases/caseProgression/withdrawApplication/withdrawApplication.ts
e2e/journeys/manageCases/createCase/dummyCase/dummyC100.ts
e2e/pages/manageCases/caseProgression/withdrawApplication/withdrawApplicationEvent1Page.ts
e2e/pages/manageCases/caseProgression/withdrawApplication/withdrawApplicationEventConfirmPage.ts
e2e/pages/manageCases/caseProgression/withdrawApplication/withdrawApplicationEventSubmitPage.ts
e2e/pages/manageCases/createCase/C100/dummyCase/dummyC100OtherPersonDetailsPage.ts
e2e/tests/manageCases/caseProgression/withdrawApplication/withdrawApplication.spec.ts

withdraw application as a solicitor

Prl 6943 - withdraw application

---

e2e/tests/manageCases/caseProgression/serviceOfApplication/serviceOfApplication.spec.ts
e2e/tests/manageCases/createCase/C100/c100AllegationsOfHarm.spec.ts

change smoke test to service of application test

---

e2e/tests/manageCases/createCase/C100/c100AllegationsOfHarm.spec.ts
e2e/tests/manageCases/createCase/C100/c100ApplicantDetails.spec.ts

Smoke test manage case change

---

e2e/pages/manageCases/createCase/C100/selectApplicationType/selectApplicationType2Page.ts
e2e/pages/manageCases/createCase/initialJourney/solicitorCreatePage.ts

Addressing test failures in jenkins build: https://build.hmcts.net/view/PRL/job/HMCTS_j_to_z_Nightly/job/prl-e2e-tests/job/master/203/
Playwright report: https://build.hmcts.net/view/PRL/job/HMCTS_j_to_z_Nightly/job/prl-e2e-tests/job/master/203/Manage_20Cases_20Chrome_20E2E_20Test_20Report/

Fixing manage case test pipeline failures

---

e2e/journeys/manageCases/caseProgression/uploadAdditionalApplications/uploadAdditionalApplications.ts
e2e/journeys/manageCases/createCase/dummyCase/dummyFL401.ts
e2e/pages/manageCases/caseProgression/amendDetails/amendApplicantDetails/amendApplicantDetails2Page.ts
e2e/pages/manageCases/caseProgression/uploadAdditionalApplications/uploadAdditionalApplications2Page.ts
e2e/pages/manageCases/createCase/C100/dummyCase/dummyC100ApplicantDetailsPage.ts
e2e/pages/manageCases/createCase/C100/miamPolicyUpgrade/miamPolicyUpgrade8Page.ts
e2e/pages/manageCases/createCase/C100/selectApplicationType/selectApplicationType2Page.ts
e2e/pages/manageCases/createCase/FL401/applicantDetails/applicantDetails1Page.ts
e2e/pages/manageCases/createCase/FL401/dummyCase/dummyFL401ApplicantDetailsPage.ts
e2e/pages/manageCases/createCase/FL401/uploadDocuments/uploadDocuments1Page.ts

This PR should fix the following failing manage cases tests on master pipeline:
manageCases/createCase/C100/c100MiamPolicyUpgrade.spec.ts
manageCases/caseProgression/amendDetails/amendApplicantDetails.spec.ts
manageCases/caseProgression/confidentialityCheck/ConfidentialityCheck.spec.ts
manageCases/caseProgression/removeLegalRepresentative/removeLegalRepresentative.spec.ts
manageCases/caseProgression/uploadAdditionalApplications/uploadAdditionalApplicationsCA.spec.ts
manageCases/caseProgression/uploadAdditionalApplications/uploadAdditionalApplicationsDA.spec.ts
manageCases/caseTabs/c100CaseTabs.spec.ts
manageCases/caseTabs/fl401CaseTabs.spec.ts
manageCases/createCase/FL401/fl401ApplicantDetails.spec.ts
manageCases/createCase/FL401/fl401StatementOfTruth.spec.ts …

Fix failing manage cases tests

---

README.md
e2e/tests/manageCases/createCase/C100/c100ApplicantDetails.spec.ts
e2e/tests/manageCases/createCase/createCase.spec.ts

recent merge to aat (welsh for professionals) have broken some tests and the content needs updating. Whilst I fix this, to unblock some devs with merge, smoke test has been changed

Change manage case smoke test

---

e2e/fixtures/citizen/caseView/makeRequestToCourtAboutCase/respondent/requestToOrderWitnessContent.ts
e2e/fixtures/citizen/caseView/makeRequestToCourtAboutCase/respondent/requestToOrderWitnessContent3.ts
e2e/fixtures/citizen/caseView/requestMoreTime/guidanceContent.ts
e2e/fixtures/citizen/caseView/requestMoreTime/helpWithFeesContent.ts
e2e/fixtures/citizen/caseView/uploadDocuments/witnessStatementsAndEvidence/uploadYourDocumentsContent.ts
e2e/fixtures/manageCases/caseProgression/uploadAdditionalApplications/uploadAdditionalApplications4Content.ts
e2e/pages/citizen/caseView/requestMoreTime/referencePage.ts
e2e/pages/citizen/caseView/uploadDocuments/witnessStatementsAndEvidence/uploadYourDocumentsPositionStatementPage.ts
e2e/pages/citizen/caseView/uploadDocuments/witnessStatementsAndEvidence/uploadYourDocumentsWitnessStatementPage.ts

Fixes to citizen nightly tests: 
- witness and position statment upload pages
- fee updates

Fix citizen tests: content change and fee updates

---

e2e/fixtures/manageCases/caseWorker/createAnOrder/OrderDA/manageOrders19DAContent.ts
e2e/fixtures/manageCases/caseWorker/createAnOrder/orderCA/manageOrders19CAContent.ts
e2e/fixtures/manageCases/caseWorker/createAnOrder/orderCA/submitCAContent.ts
e2e/pages/manageCases/caseWorker/createAnOrder/orderCA/manageOrders19Page.ts
e2e/tests/testCACaseCreator.spec.ts

Manage case tests passing locally against AAT: <img width="1178" alt="Screenshot 2025-04-04 at 12 31 40" src="https://github.com/user-attachments/assets/d49c890a-ce04-47ab-bc70-275d05bfd631" />

Fix failing pipeline tests

---

e2e/common/userHelpers/idamCreateUserApiHelper.ts
e2e/fixtures/manageCases/createCase/C100/submitAndPay/submitAndPayConfirmContent.ts
e2e/journeys/manageCases/createCase/C100.ts
e2e/journeys/manageCases/createCase/C100SubmitAndPay/C100SubmitAndPay.ts
e2e/journeys/manageCases/createCase/dummyCase/dummyC100.ts
e2e/pages/manageCases/caseWorker/createAnOrder/orderCA/manageOrders19Page.ts
e2e/pages/manageCases/createCase/C100/submitAndPay/submitAndPay1Page.ts
e2e/pages/manageCases/createCase/C100/submitAndPay/submitAndPay2Page.ts
e2e/pages/manageCases/createCase/C100/submitAndPay/submitAndPay3Page.ts
e2e/pages/manageCases/createCase/C100/submitAndPay/submitAndPayConfirmPage.ts
e2e/pages/manageCases/createCase/C100/submitAndPay/submitAndPaySubmitPage.ts

test is now passing locally against AAT: 
test is quite slow so will raise a ticket in `prl automation improvement` epic to address this

Fix failing caseTabs test

---

e2e/fixtures/manageCases/caseWorker/eidtAndApproveAnOrder/editAndApproveAnOrder21Content.ts

test passing locally against AAT:

Fix Edit and approve a CA order tests

---

e2e/pages/manageCases/createCase/C100/respondentDetails/respondentDetailsSubmitPage.ts
e2e/pages/manageCases/createCase/C100/selectApplicationType/selectApplicationType4Page.ts

turning off failing accessibility tests with exui bug raised.

Turn off failing accessibility tests

---

e2e/common/helpers.ts
e2e/pages/manageCases/caseWorker/createAnOrder/initialJourney/caseFilterPage.ts

Fix date helper function (causing create an order test to fail)

---

e2e/fixtures/manageCases/caseProgression/statementOfService/statementOfService1Content.ts
e2e/pages/manageCases/caseProgression/statementOfService/statementOfService1Page.ts

test passing locally against AAT:

Fix nightly test: change locator on statement1Page.ts

---

README.md
e2e/common/helpers.ts
e2e/tests/manageCases/createCase/createCase.spec.ts
package.json

add retry to go button on event dropdown
implement yarn playwright:visual

Fix flaky button and visual test script

---

e2e/tests/citizen/createCase/C100/c100CAJourneyWrittenConsent.spec.ts

Remove smoke tag from test temporarily

---

e2e/common/caseHelpers/citizenDACaseCreateHelper.ts
e2e/tests/manageCases/caseProgression/amendDetails/amendApplicantDetails.spec.ts

nightly dev: https://build.hmcts.net/view/PRL/job/HMCTS_j_to_z_Nightly/job/prl-e2e-tests/job/nightly-dev/44/Citizen_20Chrome_20E2E_20Test_20Report/
still two tests failing but no longer failing on DA courtnav case creation

Retry and timeout change for DA courtnav case creation 

---

e2e/fixtures/manageCases/caseProgression/caseFlags/manageFlagsAddTranslationsContent.ts
e2e/fixtures/manageCases/caseProgression/caseFlags/manageFlagsSelectCaseFlagContent.ts
e2e/fixtures/manageCases/caseProgression/caseFlags/manageFlagsUpdateCaseFlagContent.ts
e2e/journeys/manageCases/caseProgression/caseFlags/manageFlags.ts
e2e/pages/manageCases/caseProgression/caseFlags/manageFlagsAddTranslationsPage.ts
e2e/pages/manageCases/caseProgression/caseFlags/manageFlagsSelectCaseFlagPage.ts
e2e/pages/manageCases/caseProgression/caseFlags/manageFlagsUpdateCaseFlagPage.ts

Fix for the existing case flags scenarios
https://tools.hmcts.net/jira/browse/FPVTL-908
Tests results:

FPVTL-908 - fix for the existing case flags scenarios

---

e2e/caseData/citizenDA/courtNavDaCitizenCase_WithNotice.json
e2e/caseData/citizenDA/courtNavDaCitizenCase_WithoutNotice.json

Update courtnav requests to specify court location using epims number after changes from [FPVTL-413](https://tools.hmcts.net/jira/browse/FPVTL-413)
Passing createAnOrder.spec.ts "Create a power of arrest order"

Fix pipeline - update courtnav request data location

---

e2e/journeys/manageCases/caseProgression/sendToGateKeeper/sendToGateKeeperJourney.ts
e2e/tests/manageCases/caseProgression/sendToGateKeeper/sendToGateKeeper.spec.ts

Adding assertion for the DA 'Send to gatekeeper' task auto-closure, and a scenario for the Team-leader manage options.
https://tools.hmcts.net/jira/browse/FPVTL-616
latest local tests run:

FPVTL-616-adding assertion and team-leader scenario

---

Dockerfile
README.md
docker-compose.yaml
package.json

- Update visual container docker setup to be easier use
- Update Dockerfile to explicitly install playwright

Update visual container docker setup

---

renovate.json

remove renovate auto merge

---

Jenkinsfile_CNP
e2e/caseData/orderData/citizen/orderEventData-amendDischargedVaried.json
e2e/caseData/orderData/citizen/orderEventData-powerOfArrest.json
e2e/caseData/orderData/orderEventData-C43CreateOrder.json
e2e/caseData/orderData/orderEventData-amendDischargedVaried.json
e2e/caseData/orderData/orderEventData-powerOfArrest.json
e2e/caseData/solicitorCACaseEventData.json

[FPVTL-1286](https://tools.hmcts.net/jira/browse/FPVTL-1286)

Fix nightly failing tests
